import VerifiedCalculus.Logic.Omniscience
import VerifiedCalculus.Logic.Sierpinskians
import VerifiedCalculus.Logic.Kleeneans

import VerifiedCalculus.Numbers.Integer
import VerifiedCalculus.Numbers.Dyadic
import VerifiedCalculus.Numbers.ConstructiveReal
import VerifiedCalculus.Numbers.ConstructiveLowerReal
